  CREATE EXTENSION IF NOT EXISTS postgis;
  /* Setup for Edible Material */
  CREATE TABLE IF NOT EXISTS "edible_material_type"
  (
    "id"         integer                           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE           NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at" timestamp with time zone NOT NULL DEFAULT current_timestamp
  );
  /*  */
  CREATE TABLE IF NOT EXISTS "edible_material"
  (
    "id"                      integer                           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"                    varchar UNIQUE           NOT NULL,
    "edible_material_type_id" integer                  NOT NULL REFERENCES edible_material_type (id),
    "created_at"              timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at"              timestamp with time zone NOT NULL DEFAULT current_timestamp
  );
  CREATE TABLE IF NOT EXISTS "edible_material_variant"
  (
    "id"                 integer                           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"               varchar UNIQUE           NOT NULL,
    "edible_material_id" integer                  NOT NULL REFERENCES edible_material (id),
    "created_at"         timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at"         timestamp with time zone NOT NULL DEFAULT current_timestamp
  );

  /* Setup for Ingredient */
  CREATE TABLE IF NOT EXISTS "ingredient_processing"
  (
    "id"         integer                           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE           NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at" timestamp with time zone NOT NULL DEFAULT current_timestamp
  );
  CREATE TABLE IF NOT EXISTS "ingredient"
  (
    "id"         integer                           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE           NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at" timestamp with time zone NOT NULL DEFAULT current_timestamp
  );
  CREATE TABLE IF NOT EXISTS "culinary_type"
  (
    "id"         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
  );
  CREATE TABLE IF NOT EXISTS "ingredient__culinary_types"
  (
    "ingredient_id"    integer                  NOT NULL REFERENCES ingredient (id) ON DELETE CASCADE,
    "culinary_type_id" integer                  NOT NULL REFERENCES culinary_type (id) ON DELETE CASCADE,
    "created_at"       timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at"       timestamp with time zone NOT NULL DEFAULT current_timestamp,
    UNIQUE (ingredient_id, culinary_type_id)
  );

  /* Setup for Locations */
  CREATE TABLE IF NOT EXISTS "country"
  (
    "id"           integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "iso"          char(2)        NOT NULL,
    "iso3"         char(3)                  DEFAULT NULL,
    "calling_code" integer        NOT NULL,
    "name"         varchar UNIQUE NOT NULL,
    "created_at"   timestamp with time zone DEFAULT current_timestamp,
    "updated_at"   timestamp with time zone DEFAULT current_timestamp
  );
  CREATE TABLE IF NOT EXISTS "area"
  (
    "id"         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "country_id" integer        NOT NULL REFERENCES country (id) ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp,
    UNIQUE (name, country_id)
  );
  CREATE TABLE IF NOT EXISTS "farm"
  (
    "id"         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "location"   POINT,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
  );
  CREATE TABLE IF NOT EXISTS "brand"
  (
    "id"         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
  );
  /* Setup for Supplier */
  CREATE TABLE IF NOT EXISTS "supplier"
  (
    "id"         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "location"   POINT,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
  );
  /* Setup for Supply Chain Links */
  CREATE TABLE IF NOT EXISTS "supply_chain_type"
  (
    "id"         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
  );
  CREATE TABLE IF NOT EXISTS "product"
  (
    "id"                         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "brand_id"                   integer REFERENCES brand (id) ON DELETE CASCADE,
    "ingredient_id"              integer NOT NULL REFERENCES ingredient (id) ON DELETE CASCADE,
    "edible_material_variant_id" integer NOT NULL REFERENCES edible_material_variant (id) ON DELETE CASCADE,
    "created_at"                 timestamp with time zone DEFAULT current_timestamp,
    "updated_at"                 timestamp with time zone DEFAULT current_timestamp
  );
  /* Link to farm and supplier */
  CREATE TABLE IF NOT EXISTS "supply_chain_link"
  (
    "id"                   integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "product_id"           integer NOT NULL REFERENCES product (id) ON DELETE CASCADE,

    "supply_chain_type_id" integer NOT NULL REFERENCES supply_chain_type (id) ON DELETE CASCADE,
    "chain_step"           integer NOT NULL,

    "location"             POINT,
    "location_area_id"     integer REFERENCES area (id) ON DELETE CASCADE,
    "location_country_id"  integer REFERENCES country (id) ON DELETE CASCADE,

    "farm_id"              integer REFERENCES farm (id) ON DELETE CASCADE,
    "supplier_id"          integer REFERENCES supplier (id) ON DELETE CASCADE,

    "created_at"           timestamp with time zone DEFAULT current_timestamp,
    "updated_at"           timestamp with time zone DEFAULT current_timestamp
  );

  /* Setup for Retailer */
  CREATE TABLE IF NOT EXISTS "retailer"
  (
    "id"         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "country_id" integer        NOT NULL REFERENCES country (id) ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp,
    UNIQUE (name, country_id)
  );


  CREATE TABLE IF NOT EXISTS "year_segment"
  (
    "id"         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
  );

  CREATE TABLE IF NOT EXISTS "seasonal_rating"
  (
    "id"                         integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "year_segment_id"            integer NOT NULL REFERENCES year_segment (id) ON DELETE CASCADE,
    "edible_material_variant_id" integer NOT NULL REFERENCES edible_material_variant (id) ON DELETE CASCADE,
    "location"                   POINT,
    "rating"                     integer NOT NULL,
    "reference"                  varchar NOT NULL,
    "created_at"                 timestamp with time zone DEFAULT current_timestamp,
    "updated_at"                 timestamp with time zone DEFAULT current_timestamp,
    constraint max_rating
    check (rating <= 2),
    constraint min_rating
    check (rating >= 0)
  );

  CREATE TABLE IF NOT EXISTS "farmers_market"
  (
    "id"           integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"         varchar NOT NULL UNIQUE,
    "phone_number" varchar,
    "email"        varchar,
    "website"      varchar UNIQUE,
    "location"     POINT,
    "created_at"   timestamp with time zone DEFAULT current_timestamp,
    "updated_at"   timestamp with time zone DEFAULT current_timestamp
  );

  CREATE TABLE IF NOT EXISTS "farmers_market_opening_times"
  (
    "id"                integer                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "farmers_market_id" integer NOT NULL REFERENCES farmers_market (id) ON DELETE CASCADE,
    "open"              varchar NOT NULL,
    "close"             varchar NOT NULL,
    "day"               integer NOT NULL,
    "created_at"        timestamp with time zone DEFAULT current_timestamp,
    "updated_at"        timestamp with time zone DEFAULT current_timestamp,
    UNIQUE (farmers_market_id, open, close, day)
  );
