Add ingredient
Add ingredient variety
Add Area
Add Farm
Add Brand
Adjust seasonal Ratings

-- I add a a new fruit, a banana of the Cavendish variety
-- The Brand and supplier Chiquita source it from random farms in Ecuador and Cuba
-- They are sold at the rewe just near me in Berlin, Germany
-- They took 9000km to get here

CREATE TABLE IF NOT EXISTS "ingredient_type"
(
    "id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "country"
(
    "id"           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "iso"          char(2) NOT NULL,
    "iso3"         char(3)                  DEFAULT NULL,
    "calling_code" int     NOT NULL,
    "name"         varchar NOT NULL,
    "created_at"   timestamp with time zone DEFAULT current_timestamp,
    "updated_at"   timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "ingredient"
(
    "id"                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"               varchar UNIQUE           NOT NULL,
    "ingredient_type_id" integer                  NOT NULL REFERENCES ingredient_type (id) ON DELETE CASCADE,
    "created_at"         timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at"         timestamp with time zone NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "ingredient_variant"
(
    "id"            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          varchar                  NOT NULL,
    "ingredient_id" integer                  NOT NULL REFERENCES ingredient (id) ON DELETE CASCADE,
    "created_at"    timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at"    timestamp with time zone NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "brand"
(
    "id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "farm"
(
    "id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "location"   varchar UNIQUE NOT NULL,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "product"
(
    "id"                    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ingredient_variant_id" integer                  NOT NULL REFERENCES ingredient_variant (id) ON DELETE CASCADE,
    "brand_id"              integer                  NOT NULL REFERENCES brand (id) ON DELETE CASCADE,
    "created_at"            timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at"            timestamp with time zone NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "brand_sources"
(
    "id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" integer NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    "farm_id"    integer REFERENCES farm (id) ON DELETE CASCADE,
    "country_id" integer REFERENCES country (id) ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "store"
(
    "id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       integer NOT NULL REFERENCES ingredient_variant (id) ON DELETE CASCADE,
    "country_id" integer NOT NULL REFERENCES country (id) ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "store_products"
(
    "id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" integer NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    "store_id"   integer NOT NULL REFERENCES store (id) ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "store_products_accepted_sources"
(
    "id"                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "store_products_id" integer                  NOT NULL REFERENCES store_products (id) ON DELETE CASCADE,
    "brand_sources_id"  integer                  NOT NULL REFERENCES brand_sources (id) ON DELETE CASCADE,
    "created_at"        timestamp with time zone NOT NULL DEFAULT current_timestamp,
    "updated_at"        timestamp with time zone NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "year_segment"
(
    "id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "area"
(
    "id"         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar UNIQUE NOT NULL,
    "country_id" integer        NOT NULL REFERENCES country (id) ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT current_timestamp,
    "updated_at" timestamp with time zone DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS "seasonal_rating"
(
    "id"                    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "year_segment_id"       integer                  NOT NULL REFERENCES year_segment (id) ON DELETE CASCADE,
    "area_id"               integer                  NOT NULL REFERENCES area (id) ON DELETE CASCADE,
    "ingredient_variant_id" integer                  NOT NULL REFERENCES ingredient_variant (id) ON DELETE CASCADE,
    "rating"                integer                  NOT NULL,
    "created_at"            timestamp with time zone  DEFAULT current_timestamp,
    "updated_at"            timestamp with time zone  DEFAULT current_timestamp,
    constraint max_rating
        check (rating <= 2),
    constraint max_rating
        check (rating >= 0)
);